# this module sets up a list of gitignore lines for various languages
{
  crystal = ''
    /docs/
    /lib/
    /bin/
    /.shards/
    *.dwarf
  '';
  go = ''
    *.exe
    *.exe~
    *.dll
    *.so
    *.dylib
    *.test
    *.out
  '';
  nim = ''
    nimcache/
    nimblecache/
    htmldocs/
  '';
  nix = ''
    .db
    .direnv
    result*
  '';
  node = ''
    node_modules/
    logs
    *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    lerna-debug.log*
    .pnpm-debug.log*
    pids
    *.pid
    *.seed
    *.pid.lock
    coverage
    *.lcov
    .nyc_output
    build/Release
    jspm_packages/
    web_modules/
    *.tsbuildinfo
    .npm
    .eslintcache
    .stylelintcache
    .rpt2_cache/
    .rts2_cache_cjs/
    .rts2_cache_es/
    .rts2_cache_umd/
    .node_repl_history
    .yarn-integrity
    .env
    .env.development.local
    .env.test.local
    .env.production.local
    .env.local
    .cache
    .parcel-cache
    .next
    out
    .nuxt
    dist
    .serverless/
    .tern-port
    .vscode-test
    .yarn/cache
    .yarn/unplugged
    .yarn/build-state.yml
    .yarn/install-state.gz
    .pnp.*
    .svelte-kit
  '';
  python = ''
    .mypy_cache
    .ruff_cache
    .pytest_cache
    __pycache__/
    *.py[cod]
    *$py.class
    *.so
    .Python
    build/
    develop-eggs/
    dist/
    downloads/
    eggs/
    .eggs/
    lib/
    lib64/
    parts/
    sdist/
    var/
    wheels/
    share/python-wheels/
    *.egg-info/
    .installed.cfg
    *.egg
    MANIFEST
    .env
    .venv
    env/
    venv/
    ENV/
    env.bak/
    venv.bak/
  '';
  rust = ''
    debug/
    target/
    Cargo.lock
    **/*.rs.bk
    *.pdb
  '';
  terraform = ''
    **/.terraform/*
    *.tfstate
    *.tfstate.*
    crash.log
    crash.*.log
    *.tfvars
    *.tfvars.json
    override.tf
    override.tf.json
    *_override.tf
    *_override.tf.json
    .terraformrc
    terraform.rc
  '';
}
