name: check for nixpkgs-unstable updates
on: {workflow_dispatch, schedule: [cron: '0 0 * * *']}
jobs:
  nixpkgs:
    uses: jpetrucciani/nix/.github/workflows/check_update.yml@main
    with:
      tag: nixpkgs
      command: nix_hash_unstable
      path: ./sources/nixpkgs.json
    secrets:
      github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
