name: check
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  eval:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.g7c.us
            extra-trusted-public-keys = cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
      - run: nix --show-trace flake check --no-build --no-write-lock-file
  jfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.g7c.us
            extra-trusted-public-keys = cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
      - run: nix run .#jfmt -- --ci
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.g7c.us
            extra-trusted-public-keys = cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
      - run: nix --show-trace run .#scripts.check_doc_links
      - run: nix --show-trace run .#scripts.check_readme_index
  vale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.g7c.us
            extra-trusted-public-keys = cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
      - run: nix --show-trace run .#scripts.check_vale
