name: check for nixpkgs-unstable updates
on: {workflow_dispatch, schedule: [cron: '0 0 * * *']}
jobs:
  check-for-updates:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14
        extra_nix_config: |
          experimental-features = nix-command flakes
      - run: nix-env -f . -iA gh moreutils
      - run: nix shell -f . nix_hash_unstable -c nix_hash_unstable | sponge ./sources/nixpkgs.json
      - uses: peter-evans/create-pull-request@v3.10.0
        id: cpr
        with:
          delete-branch: true
          title: automatic nixpkgs update
          commit-message: automatic nixpkgs update
          branch: automatic-nixpkgs-update
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-url }}
