name: check updates workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: the name of the source to check for updates
      command:
        type: string
        required: true
        description: the command to run to generate the hashes
      path:
        type: string
        required: true
        description: the path to place the hashes
      extra_path:
        type: string
        required: false
        description: an additional path to place the hashes
    secrets:
      pat:
        required: true
        description: a personal access token with permissions to open and merge PRs to this repo

jobs:
  check-for-updates:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.pat }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix-env -f . -iA gh moreutils
      - run: nix shell -f . ${{ inputs.command }} -c ${{ inputs.command }} | sponge ${{ inputs.path }}
      - run: cp ${{ inputs.path }} ${{ inputs.extra_path }}
        if: inputs.extra_path != ''
      - uses: peter-evans/create-pull-request@v4.2.3
        id: cpr
        with:
          delete-branch: true
          title: automatic ${{inputs.tag}} update
          commit-message: automatic ${{inputs.tag}} update
          branch: automatic-${{inputs.tag}}-update
          token: ${{ secrets.pat }}
      - run: gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-url }}
