name: foundry
on: { workflow_dispatch, push: { branches: [main] } }
jobs:
  build_v2:
    env:
      REGISTRIES_CONF: /tmp/containers/registries.conf
    strategy:
      fail-fast: false
      matrix:
        image:
          - certbot
          - certbot_aws
          - certbot_cloudflare
          - certbot_google
          - certbot_porkbun
          - curl
          - argohex
          - hex
          - k8s_aws
          - k8s_gcp
          - nix
          # - pypi
          - python312
          - python313
          - python314
          - zaddy
    name: foundry-${{ matrix.image }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.g7c.us
            extra-trusted-public-keys = cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
      - name: skopeo fixes
        run: |
          mkdir -p /tmp/containers
          touch /tmp/containers/registries.conf
      - run: nix run .#skopeo -- login --registries-conf "$REGISTRIES_CONF" -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io
      - run: nix run --impure .#foundry.${{ matrix.image }}.copyToRegistry
      - run: |
          image="docker://$(nix eval --impure --raw .#foundry.${{ matrix.image }}.imageName)"
          tag="$(nix eval --impure --raw .#foundry.${{ matrix.image }}.imageTag)"
          skopeo --registries-conf "$REGISTRIES_CONF" --insecure-policy copy --retry-times 2 "$image:$tag" "$image:$(date +"%F")"
          skopeo --registries-conf "$REGISTRIES_CONF" --insecure-policy copy --retry-times 2 "$image:$tag" "$image:latest"
