name: build
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
    name: nix (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: jacobi
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix -vL --show-trace build -f . extra-packages home-packages
