name: statix
on: {workflow_dispatch, push: {branches: [main]}, pull_request}
jobs:
  statix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix-env -f . -iA statix
      - run: statix check || true
